### ISSUE TITLE
OauthApi.getOauthToken有时会发生400 Bad Request

### ISSUE THREAD

**Issue by macthink** [foxinmy/weixin4j#11]
以下是过程日志：

[http-apr-8088-exec-4] INFO  cn.macthink.map.web.controller.ActLotteryController - com.foxinmy.weixin4j.exception.WeixinException: com.foxinmy.weixin4j.http.HttpClientException: 400 Bad Request
	at com.foxinmy.weixin4j.http.weixin.WeixinRequestExecutor.doRequest(WeixinRequestExecutor.java:129)
	at com.foxinmy.weixin4j.http.weixin.WeixinRequestExecutor.get(WeixinRequestExecutor.java:52)
	at com.foxinmy.weixin4j.mp.api.OauthApi.getOauthToken(OauthApi.java:89)
	at cn.macthink.map.web.controller.ActLotteryController.index(ActLotteryController.java:106)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.jfinal.core.ActionInvocation.invoke(ActionInvocation.java:55)
	at cn.macthink.map.web.interceptor.ActLotteryStatusInterceptor.intercept(ActLotteryStatusInterceptor.java:60)
	at com.jfinal.core.ActionInvocation.invoke(ActionInvocation.java:51)
	at cn.macthink.jfinalbase.ext.core.interceptor.ExceptionInterceptor.intercept(ExceptionInterceptor.java:37)
	at com.jfinal.core.ActionInvocation.invoke(ActionInvocation.java:51)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:77)
	at cn.macthink.jfinalbase.ext.core.handler.xss.XssHandler.handle(XssHandler.java:19)
	at cn.macthink.jfinalbase.ext.core.handler.SessionHandler.handle(SessionHandler.java:51)
	at cn.macthink.map.web.handler.AppHandler.handle(AppHandler.java:21)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:72)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2463)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2452)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.foxinmy.weixin4j.http.HttpClientException: 400 Bad Request
	at com.foxinmy.weixin4j.http.AbstractHttpClient.handleResponse(AbstractHttpClient.java:122)
	at com.foxinmy.weixin4j.http.factory.HttpComponent4_2.execute(HttpComponent4_2.java:74)
	at com.foxinmy.weixin4j.http.weixin.WeixinRequestExecutor.doRequest(WeixinRequestExecutor.java:96)
	... 34 more

**Comment by foxinmy** [comment]
感谢反馈。
HttpClient 是根据项目的运行环境去确定的 具体是
NettyHttpClient -> ApachHttpClient -> SimpleHttpClient(HttpURLConnection)
代码可以见com.foxinmy.weixin4j.http.factory.HttpClientFactory

看异常日志项目里应该是引用了Apache的HttpClient包 请把版本号发下

然后 有一个临时的解决方案是 用 jdk自带的 HttpURLConnection

代码为 在项目启动时调用

    HttpClientFactory.setDefaultFactory(new SimpleHttpClientFactory());

表示有关微信所有的请求都将会用 HttpURLConnection 去处理 

因为Apache的HttpClient包测试用例比较少 ＝ ＝ 

还有麻烦把weixin4j的版本号也发下。

感谢使用。

**Comment by macthink** [comment]
谢谢weixin4j，用起来很方便，代码质量也很高。

weixin4j-mp: 1.6.0
httpclient: 4.4

**Comment by laotu5i0** [comment]
我也遇到此问题。我用的版本是：1.6.3
不知道现在的最新版本有没有解决此问题呢？

**Comment by foxinmy** [comment]
@laotu5i0 请使用1.6.5
