### ISSUE TITLE
weixinProxy.getUser报错

### ISSUE THREAD

**Issue by raykwan** [foxinmy/weixin4j#128]
响应结果的"order":[0]，User类的order为int

Exception in thread "main" com.alibaba.fastjson.JSONException: can not cast to int, value : [0]
	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:969)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:648)
	at com.alibaba.fastjson.JSON.toJavaObject(JSON.java:965)
	at com.foxinmy.weixin4j.qy.api.UserApi.getUser(UserApi.java:151)
	at com.foxinmy.weixin4j.qy.WeixinProxy.getUser(WeixinProxy.java:741)

**Comment by foxinmy** [comment]
感谢反馈。这是万恶的微信改了数据协议，由原来的字符串变成了数组类型。
我将修复此问题，在下个版本可用。
