### ISSUE TITLE
用户管理时，当某个用户有扩展字段，报错

### ISSUE THREAD

**Issue by looly** [foxinmy/weixin4j#14]
调用weixin.getUser("XXX");

```
Exception in thread "main" com.alibaba.fastjson.JSONException: com.foxinmy.weixin4j.qy.model.NameValue.<init>()
	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:872)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:550)
	at com.alibaba.fastjson.JSON.toJavaObject(JSON.java:701)
	at com.foxinmy.weixin4j.qy.api.UserApi.getUser(UserApi.java:156)
	at com.foxinmy.weixin4j.qy.WeixinProxy.getUser(WeixinProxy.java:615)
	at com.xiaoleilu.ga.weixin.UserService.main(UserService.java:11)
Caused by: com.alibaba.fastjson.JSONException: com.foxinmy.weixin4j.qy.model.NameValue.<init>()
	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:872)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:550)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:560)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:701)
	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:858)
	... 5 more
Caused by: java.lang.NoSuchMethodException: com.foxinmy.weixin4j.qy.model.NameValue.<init>()
	at java.lang.Class.getConstructor0(Class.java:2892)
	at java.lang.Class.getDeclaredConstructor(Class.java:2058)
	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:843)
	... 9 more
```

**Comment by foxinmy** [comment]
感谢反馈，已修复，等待下一次release。预计明天。
