### ISSUE TITLE
线程安全问题导致的FWK005错误

### ISSUE THREAD

**Issue by looly** [foxinmy/weixin4j#20]
```java
java.lang.IllegalArgumentException: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXException: FWK005 parse may not be called while parsing.]
	at com.foxinmy.weixin4j.xml.XmlStream.fromXML(XmlStream.java:87) ~[weixin4j-base-1.6.5.jar:na]
	at com.foxinmy.weixin4j.token.FileTokenStorager.lookup(FileTokenStorager.java:34) ~[weixin4j-base-1.6.5.jar:na]
	at com.foxinmy.weixin4j.token.FileTokenStorager.lookup(FileTokenStorager.java:20) ~[weixin4j-base-1.6.5.jar:na]
	at com.foxinmy.weixin4j.token.TokenHolder.getToken(TokenHolder.java:47) ~[weixin4j-base-1.6.5.jar:na]
	at com.foxinmy.weixin4j.qy.api.NotifyApi.sendNotifyMessage(NotifyApi.java:84) ~[weixin4j-qy-1.6.5.jar:na]
	at com.foxinmy.weixin4j.qy.WeixinProxy.sendNotifyMessage(WeixinProxy.java:174) ~[weixin4j-qy-1.6.5.jar:na]
```

在批量推送消息的时候出现以上问题，每个推送一个线程。就会出现这个错误。5个消息成功3个，我查了下，线程问题。

文章在此，希望参考http://www.blogjava.net/wilesun/archive/2012/05/09/377723.html

我看你代码中Unmarshaller是单例的，可能引发这个问题。希望解决。

**Comment by foxinmy** [comment]
刚试了下 确实有这样的问题 感谢反馈。

预计明天升级版本。
