### ISSUE TITLE
Netty4HttpClientFactory是不是有点问题啊..

### ISSUE THREAD

**Issue by n59yl** [foxinmy/weixin4j#29]
base的那个test...运行一次之后不关闭..不太懂nio这块...不需要关么..?
然后...我循环访问1w次 helloworld 界面....HttpComponent4Factory在5k左右报错..Netty4HttpClientFactory在4k左右报错

**Comment by foxinmy** [comment]
感谢 反馈；
在 HttpClient实现里面的execute方法都会关闭资源的。
可以参考：com.foxinmy.weixin4j.http.factory.Netty4HttpResponse类
最后提示错误的是什么？

**Comment by n59yl** [comment]
Exception in thread "main" java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:68)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:44)
	at com.foxinmy.weixin4j.http.factory.Netty4HttpClientFactory.newInstance(Netty4HttpClientFactory.java:50)
	at com.foxinmy.weixin4j.http.factory.HttpClientFactory.getInstance(HttpClientFactory.java:81)
	at com.foxinmy.weixin4j.base.test.HttpClientTest.test4(HttpClientTest.java:55)
	at com.foxinmy.weixin4j.base.test.HttpClientTest.main(HttpClientTest.java:79)
Caused by: io.netty.channel.ChannelException: failed to open a new selector
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:128)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:120)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:87)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
	... 8 more
Caused by: java.io.IOException: Unable to establish loopback connection
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:125)
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:69)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:141)
	at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50)
	at java.nio.channels.Pipe.open(Pipe.java:150)
	at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:126)
	at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:126)
	... 11 more
Caused by: java.net.SocketException: Permission denied: connect
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:364)
	at sun.nio.ch.Net.connect(Net.java:356)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:623)
	at java.nio.channels.SocketChannel.open(SocketChannel.java:184)
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:97)
	... 19 more

**Comment by foxinmy** [comment]
测试代码 咋写的,直接这样：

     for(int i=0;i<100000;i++){
		test1();
		}

windows下打开NIO的通道貌似数量有限 循环1w每次都获取一个 Netty4HttpClient实例
我看看能不能改进下

**Comment by n59yl** [comment]
哥们很nice~
