### ISSUE TITLE
阿里云部署的web项目请求微信接口发起https请求总是失败

### ISSUE THREAD

**Issue by zhangxingbo1987** [foxinmy/weixin4j#31]
阿里云CentOS上OpenJDK的环境就不行。
[root@iZ25pwy5tqpZ logs]# java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (rhel-2.6.2.2.el6_7-x86_64 u91-b00)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
控制台报错如下 
javax.net.ssl.SSLException: java.security.ProviderException: java.security.KeyException 
-----------------------------------------------------------------------------------------------------------------
如果阿里云CentOS上 OpenJdk换成普通oracle jdk测试没有问题
[root@iZ25pwy5tqpZ ~]# java -version
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) Server VM (build 24.71-b01, mixed mode)
[root@iZ25pwy5tqpZ ~]#

作者 看能重代码上来处理吗？？

**Comment by foxinmy** [comment]
我本地安装的openjdk1.7测试通过：
![image](https://cloud.githubusercontent.com/assets/1318274/12693995/c6c058e6-c758-11e5-9aa8-d7b487c0b054.png)

能否贴全部的异常信息？

**Comment by zhangxingbo1987** [comment]
com.foxinmy.weixin4j.exception.WeixinException: com.foxinmy.weixin4j.http.HttpClientException: I/O error on GET request for "https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential**&appid=wx44fee1c1148e****&secret=******9dac1d10984c22e0f3eafe93fae**":peer not authenticated
        at com.foxinmy.weixin4j.http.weixin.WeixinRequestExecutor.doRequest(WeixinRequestExecutor.java:129)
        at com.foxinmy.weixin4j.http.weixin.WeixinRequestExecutor.get(WeixinRequestExecutor.java:52)
        at com.foxinmy.weixin4j.mp.token.WeixinTokenCreator.createToken(WeixinTokenCreator.java:50)
        at com.foxinmy.weixin4j.token.TokenHolder.getToken(TokenHolder.java:49)
        at com.foxinmy.weixin4j.token.TokenHolder.getAccessToken(TokenHolder.java:62)
        at com.foxinmy.weixin4j.mp.api.MenuApi.createMenu0(MenuApi.java:60)
        at com.foxinmy.weixin4j.mp.api.MenuApi.createMenu(MenuApi.java:55)
        at com.foxinmy.weixin4j.mp.WeixinProxy.createMenu(WeixinProxy.java:1104)
        at com.jx.wx.menu.bussiness.WxMenuDS.weixinMenuSynchronous(WxMenuDS.java:301)
        at com.jx.wx.menu.bussiness.WxMenuDS$$FastClassByCGLIB$$e6cc5305.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:698)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:631)
        at com.jx.wx.menu.bussiness.WxMenuDS$$EnhancerByCGLIB$$19cbfa3d.weixinMenuSynchronous(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.xt.ssb.util.bean.ReflectAssists.callMethod(ReflectAssists.java:265)
        at com.xt.ssb.web.JsonpServiceServlet.callMethod(JsonpServiceServlet.java:141)
        at com.xt.ssb.web.JsonpServiceServlet.dispatcher(JsonpServiceServlet.java:78)
        at com.xt.ssb.web.JsonpServiceServlet.doPost(JsonpServiceServlet.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at com.xt.ssb.web.SessiontimeoutFilter.doFilter(SessiontimeoutFilter.java:95)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:152)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.foxinmy.weixin4j.http.HttpClientException: I/O error on GET request for "https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=wx44fee1c1148ecc35&secret=63adb9dac1d10984c22e0f3eafe93fae":peer not authenticated
        at com.foxinmy.weixin4j.http.factory.HttpComponent4_1.execute(HttpComponent4_1.java:109)
        at com.foxinmy.weixin4j.http.weixin.WeixinRequestExecutor.doRequest(WeixinRequestExecutor.java:96)
        ... 57 more
Caused by: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
        at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:421)
        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:692)
        at org.apache.http.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:640)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
        at com.foxinmy.weixin4j.http.factory.HttpComponent4_1.execute(HttpComponent4_1.java:103)
        ... 58 more

**Comment by foxinmy** [comment]
测试通过，暂时关闭。
