### ISSUE TITLE
关于项目中已引用了commons-httpclient包，导致报错。

### ISSUE THREAD

**Issue by smallfire3** [foxinmy/weixin4j#67]
项目中已使用了commons-httpclient包，现在加入weixin4j 的jar包后，测试时调用api报错。
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.httpclient.params.HttpMethodParams.setUriCharset(Ljava/lang/String;)V
	at com.foxinmy.weixin4j.http.factory.HttpComponent3.execute(HttpComponent3.java:120)
	at com.foxinmy.weixin4j.http.weixin.WeixinRequestExecutor.doRequest(WeixinRequestExecutor.java:102)
	at com.foxinmy.weixin4j.http.weixin.WeixinRequestExecutor.post(WeixinRequestExecutor.java:81)
	at com.foxinmy.weixin4j.qy.api.PartyApi.createParty(PartyApi.java:53)
	at com.foxinmy.weixin4j.qy.WeixinProxy.createParty(WeixinProxy.java:550)
	at com.wx.WxTest.main(WxTest.java:22)

求指导，万分感谢！

**Comment by foxinmy** [comment]
感谢反馈，请问commons-httpclient包是什么版本？

**Comment by smallfire3** [comment]
3.0

**Comment by foxinmy** [comment]
确认为bug，已修复，请关注最新代码。
