### ISSUE TITLE
微信订单查询接口报错

### ISSUE THREAD

**Issue by miaoxinwei** [foxinmy/weixin4j#95]
博主，在使用中发现，多线程调用微信订单查询接口会报错

以下是具体错误：
Caused by: java.lang.RuntimeException: javax.xml.bind.UnmarshalException
- with linked exception:
  [org.xml.sax.SAXException: FWK005 parse may not be called while parsing.]
  at com.foxinmy.weixin4j.xml.XmlStream.fromXML(XmlStream.java:86)
  at com.foxinmy.weixin4j.http.message.XmlMessageConverter.convertInternal(XmlMessageConverter.java:49)
  at com.foxinmy.weixin4j.http.message.AbstractMessageConverter.convert(AbstractMessageConverter.java:91)
  at com.foxinmy.weixin4j.http.weixin.WeixinRequestExecutor.handleResponse(WeixinRequestExecutor.java:189)
  at com.foxinmy.weixin4j.http.weixin.WeixinRequestExecutor.doRequest(WeixinRequestExecutor.java:135)
  at com.foxinmy.weixin4j.http.weixin.WeixinRequestExecutor.post(WeixinRequestExecutor.java:73)
  at com.foxinmy.weixin4j.api.PayApi.queryOrder(PayApi.java:393)
  at com.foxinmy.weixin4j.payment.WeixinPayProxy.queryOrder(WeixinPayProxy.java:418)
  at com.fshows.liquidator.platform.openapi.service.OrderService.WxpayTradeQuery(OrderService.java:459)
  at com.fshows.liquidator.platform.openapi.service.api.ApiControllerService.orderAlipayOrderQueryController(ApiControllerService.java:391)
  ... 45 more
  Caused by: javax.xml.bind.UnmarshalException
- with linked exception:
  [org.xml.sax.SAXException: FWK005 parse may not be called while parsing.]
  at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
  at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:563)
  at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:249)
  at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:221)
  at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:276)
  at com.foxinmy.weixin4j.xml.XmlStream.fromXML(XmlStream.java:80)
  ... 54 more
  Caused by: org.xml.sax.SAXException: FWK005 parse may not be called while parsing.
  at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1253)
  at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
  at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
  ... 57 more

请问有什么好的解决办法吗

**Comment by foxinmy** [comment]
感谢反馈。

确实是多线程导致的错误，我看看要怎么改。

感谢使用。

**Comment by catinred2** [comment]
在我们的项目中也发现，XmlStream反序列化的时候会有线程安全问题。改用jackson来反序列化就没事了。

**Comment by foxinmy** [comment]
@catinred2 嗯 xmlstream会有这个问题，我已在代码中做了控制，请使用1.7.2。

**Comment by miaoxinwei** [comment]
@foxinmy  博主 现在并发的话 好像有时候会大量报出 httpclient错误  
ex = com.foxinmy.weixin4j.http.HttpClientException: I/O error on POST request for "https://api.mch.weixin.qq.com/pay/orderquery":Request aborted
        at com.foxinmy.weixin4j.xml.XmlStream.fromXML(XmlStream.java:55)
        at com.foxinmy.weixin4j.http.message.XmlMessageConverter.convertInternal(XmlMessageConverter.java:49)
        at com.foxinmy.weixin4j.http.message.AbstractMessageConverter.convert(AbstractMessageConverter.java:91)
        at com.foxinmy.weixin4j.http.weixin.WeixinResponse.getAsObject(WeixinResponse.java:73)
        at com.foxinmy.weixin4j.http.weixin.WeixinResponse.getAsResult(WeixinResponse.java:56)
        at com.foxinmy.weixin4j.http.weixin.WeixinRequestExecutor.handleResponse(WeixinRequestExecutor.java:181)
        at com.foxinmy.weixin4j.http.weixin.WeixinRequestExecutor.doRequest(WeixinRequestExecutor.java:135)
        at com.foxinmy.weixin4j.http.weixin.WeixinRequestExecutor.post(WeixinRequestExecutor.java:73)
        at com.foxinmy.weixin4j.api.PayApi.queryOrder(PayApi.java:393)
        at com.foxinmy.weixin4j.payment.WeixinPayProxy.queryOrder(WeixinPayProxy.java:418)
        at com.foxinmy.weixin4j.xml.XmlStream.fromXML(XmlStream.java:55)
        at com.foxinmy.weixin4j.http.message.XmlMessageConverter.convertInternal(XmlMessageConverter.java:49)
        at com.foxinmy.weixin4j.http.message.AbstractMessageConverter.convert(AbstractMessageConverter.java:91)
        at com.foxinmy.weixin4j.http.weixin.WeixinResponse.getAsObject(WeixinResponse.java:73)
        at com.foxinmy.weixin4j.http.weixin.WeixinResponse.getAsResult(WeixinResponse.java:56)
        at com.foxinmy.weixin4j.http.weixin.WeixinRequestExecutor.handleResponse(WeixinRequestExecutor.java:181)
        at com.foxinmy.weixin4j.http.weixin.WeixinRequestExecutor.doRequest(WeixinRequestExecutor.java:135)
        at com.foxinmy.weixin4j.http.weixin.WeixinRequestExecutor.post(WeixinRequestExecutor.java:73)
        at com.foxinmy.weixin4j.api.PayApi.queryOrder(PayApi.java:393)
        at com.foxinmy.weixin4j.payment.WeixinPayProxy.queryOrder(WeixinPayProxy.java:418)

**Comment by foxinmy** [comment]
请问使用的版本是？

这个问题是多线程去解析xml造成的，在`1.7.2`做了一些处理。、

感谢使用。

**Comment by miaoxinwei** [comment]
@foxinmy  我们是在1.7.1的基础上修改的 直接用的1.7.2里面的xmlsteam

**Comment by foxinmy** [comment]
那可以对照一下代码，我改了几个点，主要是控制xml转换的时候只有一个实例操作：

```java
private final static ConcurrentHashMap<Class<?>, JAXBContext> jaxbContexts = new ConcurrentHashMap<Class<?>, JAXBContext>();
```

```java
private static JAXBContext getJaxbContext(Class<?> clazz) {
		JAXBContext jaxbContext = jaxbContexts.get(clazz);
		if (jaxbContext == null) {
			try {
				jaxbContext = JAXBContext.newInstance(clazz);
				jaxbContexts.putIfAbsent(clazz, jaxbContext);
			} catch (JAXBException ex) {
				throw new RuntimeException(
						"Could not instantiate JAXBContext for class [" + clazz
								+ "]: " + ex.getMessage(), ex);
			}
		}
		return jaxbContext;
	}
```

```java
JAXBContext jaxbContext = getJaxbContext(clazz);
		try {
			Unmarshaller unmarshaller = jaxbContext.createUnmarshaller();
			Source source = new StreamSource(content);
			XmlRootElement rootElement = clazz
					.getAnnotation(XmlRootElement.class);
			if (rootElement == null
					|| rootElement.name().equals(
							XmlRootElement.class.getMethod("name")
									.getDefaultValue().toString())) {
				JAXBElement<T> jaxbElement = unmarshaller.unmarshal(source,
						clazz);
				return jaxbElement.getValue();
			} else {
				return (T) unmarshaller.unmarshal(source);
			}
```
